### ISSUE TITLE
how to use this service ? 

### ISSUE THREAD

**Issue by kaiyes** [AnomalyInnovations/serverless-es7#13]
Hi,  will installing the package automatically give me async - await functionality when I deploy to lambdas or there other steps required ?

**Comment by jayair** [comment]
@kaiyes No that is pretty much it. Just follow the instructions in the README.

**Comment by kaiyes** [comment]
@jayair  thanks. I understand this is a boilerplate. I was trying to add async - await+import in my existing app. For that, I guess I will have to follow your other [tutorial ](https://serverless-stack.com/chapters/add-support-for-es6-es7-javascript.html)
